### ISSUE TITLE
Please add RCON to Waterfall

### ISSUE THREAD

**Issue by pernicius** [WaterfallMC/Waterfall#694]
Please add RCON to Waterfall like in Paper/Spigot. It is so much more elegant to manage the server espezial in an linux environment where all servers are controled via systemd.

(sry for my bad english, i'm german)

**Comment by Xernium** [comment]
That kind of feature is outside the scope of Bungeecord or Waterfall for that matter. 
The effort of maintaining that feature doesn't pay off, not to mention the additional risks it brings to the table; I'm very certain there aren't enough people who would benefit from having this feature. 
Also we generally don't accept requests for features which can be very easily added using plugins, that holds true in this case as well, see: https://github.com/orblazer/bungee-rcon

Und jetzt auch noch auf Deutsch: 
Als Feature wäre RCON relativ fernab der Ziele von Bungeecord und aber auch Waterfall. 
Der Aufwand also kosten/nutzen für dieses Feature und die zusätzlichen Risiken, die es mit sich bringt, sind zu groß, um es als Feature zu rechtfertigen. 
Es wäre dann noch zu beachten, dass dieses Feature relativ leicht auch durch Plugins zur Verfügung gestellt werden kann, wie zum Beispiel durch dieses hier: https://github.com/orblazer/bungee-rcon

**Comment by electronicboy** [comment]
rcon already causes enough issues in other aspects of mc given that it's shoed in and there's no real API to represent the concepts, rcon itself is not something where there is much traction behind, it misses out a lot of stuff to the sense that I'm more waiting on for the day of something sane rather than something which was created far too many years ago, without any form of security, which has been shoehorned many times to the sense that there are multiple variants of rcon because of the fact that it's stupidly limited (rcon doesn't even have proper support for unicode last I knew, it was more an unofficial offspec which people kinda adopted and creates even more issues)

There are plugins available, as noted above, I don't think that there is enough demand for this for me to deal with the horrors of supporting rcon and all it's bastardisations, I'd be much more open towards something modern which supports even basic security features (outside of plain string passwords transmitted over the network), as well as actually being a proper remote console, paperd is probs the cloest I've seen to this, but, no idea if it will be adoptable to waterfall (or if the final remaining major stopper on that is fixable)

**Comment by pernicius** [comment]
thx for these really detailed answers ... i see it's not a good idea

thank you very much
