### ISSUE TITLE
Slow join times for 1.8

### ISSUE THREAD

**Issue by ky678** [WaterfallMC/Waterfall#781]
When using a 1.8.8 paper server with 1.8.9 client and waterfall-504, it takes 13 seconds to join the server. I did not make any changes to the server files except setting online-mode=false in server.properties. Replacing the jar with bungeecord fixes it. All of this is done on the same pc and the client is 1.8.9 with optifine.

Waterfall log file (Does not show any errors)
[latest.log](https://github.com/PaperMC/Waterfall/files/9792796/latest.log)

Config.yml (Default) https://pastebin.com/PHrW0K0q
Waterfall.yml (Also Default) https://pastebin.com/5vfBDhuE
server.properties (Default except online-mode=false) https://pastebin.com/YuQvHjFs

Please don't ask me for more details unless 
- you are unable to recreate the issue
- you are from the dev team and actually plans on fixing this issue if it is real (Lots of devs do not care about 1.8)

**Comment by electronicboy** [comment]
primary thing is gonna be suggesting to disable things like netty/async DNS inside of the waterfall config, otherwise, I don't have the means to even try to reproduce this (nor does it seem like much of an issue outside of the years long misnomer where some people have stupidly long join times on bungee/waterfall in general, sometimes in which switching between the two can resolve it)

**Comment by ky678** [comment]
> primary thing is gonna be suggesting to disable things like netty/async DNS inside of the waterfall config, otherwise, I don't have the means to even try to reproduce this (nor does it seem like much of an issue outside of the years long misnomer where some people have stupidly long join times on bungee/waterfall in general, sometimes in which switching between the two can resolve it)

Disabling use_netty_dns_resolver fixed it. Thank you.
