### ISSUE TITLE
Chat message validation

### ISSUE THREAD

**Issue by PancakeCatsss** [WaterfallMC/Waterfall#800]
I'm not sure if this is a bug or not but figured I would post it here just in case it is. 

Canceling the ChatEvent causes the player to be kicked because of Chat message validation. 

I have tested this is normal BungeeCord connected to a Spigot server and this is not an issue. However using waterfall and a paper server this is an issue. 

https://www.youtube.com/watch?v=00VkB137N7I&ab_channel=PancakeSyrup

Waterfall Version: git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e0a029e:520
Paper Version: git-Paper-466
Client Version: 1.19.4

**Comment by electronicboy** [comment]
canceling a chat message will mess up the chat chain, there is a slim chance that spigot just doesn't support chat signing and basically just ignores that stuff, whereas paper actually has support for it. generally nothing we can do without adding a mechanism to sync the chain to the backend instance, which was a WIP for velocity but afaik was somewhat stalled due to the mess created by older versions.

**Comment by PancakeCatsss** [comment]
Thanks for the reply, kinda wish being able to cancel that event was removed then since you really can't be doing that without causing this issue.
