### ISSUE TITLE
[04:56:11 WARN]: [<IP>] <-> InitialHandler - bad packet, are mods in use!? Couldn't read all bytes from a packet. For more information, launch Waterfall with -Dwaterfall.packet-decode-logging=true

### ISSUE THREAD

**Issue by HandsomeshadowYT** [WaterfallMC/Waterfall#801]
My console is continously being spammed by the message 

"[04:56:11 WARN]: [<IP>] <-> InitialHandler - bad packet, are mods in use!? Couldn't read all bytes from a packet. For more information, launch Waterfall with -Dwaterfall.packet-decode-logging=true"

I actually dont know whats causing it can you please help im kinda new to this

**Comment by Janmm14** [comment]
Usually this is caused by unsupported mods, people putting the server url and port into a browser or ddos attempts.

To leanr more details, start your waterfall with `-Dwaterfall.packet-decode-logging=true` before `-jar` argument unitl you get such an error again - it will contain information needed to judge details.

In order to limit impsact of ddos attempts you should remove this added parameter from your waterfall startup script again at some point afterwards.

**Comment by electronicboy** [comment]
Closing due to lack of response, as said, youd need to use that flag to work out what packet it's generally upset with and where
