### ISSUE TITLE
Error dispatching event ServerKickEvent

### ISSUE THREAD

**Issue by Zapry** [WaterfallMC/Waterfall#832]
Hello! I recently made a change to Waterfall (I came from using BungeeCord) and when I changed it in the console, many warns began to be flagged. They don't always come out but they do come out very often. These come out when a user logs out. My server is 1.20.2 and I am using the latest version of Waterfall. I want to add that I use ViaVersion which allows users from 1.16 onwards to enter

Here i give u a bin about the warn: https://pastebin.com/WPLKawtN

**Comment by Janmm14** [comment]
99% its a problem of plugin movemenow.
To get a useful issue report to movemenow plugin dev: Consult the first log file after proxy start to get errors with a stack trace (stack trace = which functions were called presented as a bunch of lines containing " at " at the start after the error text you've shown.
The reason your error might not have a stack trace is tht the jvm will stop creating this error information if one specific error is happening many, many times to optimize performance and because there will likely be countless mentions of the same error already in a log file somewhere.

**Comment by electronicboy** [comment]
Waterfall fires the ServerKickEvent in more cases than bungeecord does, this is generally down to the plugin not handing that
